### ISSUE TITLE
BUG: End of Act irregularities on first read-through (azw3)

### ISSUE THREAD

**Issue by James-deWitt** [standardebooks/karel-capek_r-u-r_paul-selver_nigel-playfair#2]
I downloaded the azw3 e-book of R.U.R. and while reading through it the first time, every time I turned the page at the end of the chapter I would not advance to the next chapter, but instead be put back many pages in the current chapter. This only happened the first time going through the text, but it happened at the end of every act/epilogue.

Device Model: Kindle Paperwhite (2017)
Firmware Version: Kindle 5.13.6 (3731990038)

Not sure if related, but I've followed the instructions on downloading the thumbnails and it hasn't worked of any of the azw3 ebooks

**Comment by acabal** [comment]
Unfortunately this is a bug with the Kindle renderer. Nothing we can do about it since the ebook source is correct. I typically suggest getting a different brand of ereader as Kindles are notoriously buggy.
